import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./layout.global.scss"
import { Provider } from "./context";
import { Indicator } from "./indicator/indicator";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <Indicator />
          {children}
        </Provider>
      </body>
    </html>
  );
}
